theme: jekyll-theme-architect

# head
title: 深圳DIY - SZDIY Community

# sidebar header
info:
    title: 深圳DIY
    description: Welcome to SZDIY/Maker Community


sidebar:
  items:
    - title: Intro 社区介绍
      link: /intro

    - title: Meetup 聚会
      link: /meetup

    - title: Participate 如何参与
      link: /participate

    - title: Membership 会员制度
      link: /membership

    - title: Tools 工具列表
      link: /tools

    - title: Projects 项目
      link: /projects

    - title: Members 认证会员
      link: /members

    - title: History 历史
      link: /history

    - title: Culture 社区文化
      link: /culture

    - title: Sponsors 赞助
      link: /sponsors

social:
  github:
    title: GitHub
    link: https://github.com/szdiy
  fediverse:
    title: Social
    link: https://szdiy.social/
  gallery:
    title: Gallery
    link: https://gallery.szdiy.soraharu.com/
  flickr:
    title: Flickr 
    link: https://www.flickr.com/photos/szdiy
  wechat:
    title: "WeChat: szdiyorg"
  admin:
    title: "Admin: szdiyadm[at]gmail.com"

plugins:
  - jekyll-loading-lazy
